### ISSUE TITLE
difference in size of select inputs and normal input fields

### ISSUE THREAD

**Issue by r3wt** [sapo/Ink#362]
select inputs are about 2 px larger than normal input fields

here's a test case with two selects and an input type="number" in an inline control group.

http://162.243.238.152/?p=register

here is a simplified(values removed from select inputs for shortness) version of my code

```html
<div class="control-group required">
	<label>Enter Your Date Of Birth<a href="#">(Why Am I being asked for this?)</a></label> 
	<div class="column-group">
		<div class="control all-33 small-100 tiny-100">
			<label for="month">Month</label>
			<select name="month" value="">
				<option value="01">January</option>
			</select>
		</div>
		<div class="control all-33 small-100 tiny-100">
			<label for="date">Day</label>
			<select name="date" >
				<option value="01">01</option>
			</select>
		</div>
		<div class="control all-33 small-100 tiny-100">
			<label for="year">Year(YYYY)</label>
			<input type="number" name="year" min="1900" max="2014" value="2014">
		</div>
	</div>
	<p class="tip"><strong>Tip:</strong>You must be 18 or older to register</p>
</div>
```

**Comment by gnpfonseca** [comment]
Hey,

After getting back to this issue, we came to the conclusion that it's impossible to normalize the height of all of the input fields without setting a fixed heigh. And this would break some other cool features such as appended and prepended buttons.

So what i would recommend is that you set an height for the form field elements. If you are using our `$base-font-size` settings, 41px should work.

```css
.ink-form input[type=color], 
.ink-form input[type=date], 
.ink-form input[type=datetime-local], 
.ink-form input[type=datetime], 
.ink-form input[type=email], 
.ink-form input[type=month], 
.ink-form input[type=number], 
.ink-form input[type=password], 
.ink-form input[type=search], 
.ink-form input[type=tel], 
.ink-form input[type=text],
.ink-form input[type=time], 
.ink-form input[type=url],
.ink-form input[type=week], 
.ink-form select, .ink-form textarea {
    height: 41px;
}
```
